#!/bin/sh


pkill -2 nodeos && sleep 20 

ps -ef | grep "nodeos"
echo Make sure nodeos quitted
read

rm nohup.out

# nohup nodeos --contracts-console -d /mnt/data &

# nohup nodeos --verbose-http-errors -d /mnt/data &

nohup nodeos -d /mnt/data &

